### PR TITLE
Removed Propaganda

### PR DESCRIPTION
**Pull request by Cholowao**
This is a package that will be used by many people, not only Western who wants to invade Russia. Please remove politics.

Thanks

### CODE REVIEW

**Comment by stalniy** [comment]
don’t use the package if you don’t want. This will stay there for a long time  

your russians kill civilians!

**Comment by Cholowao** [comment]
I have been a member for long, I was wondering why this is free and how you
get money, but now I realise its because of commission you receive. While I
am not against receiving commissions but I thinki don't support what
sponsored you. I will not migrate now, and thanks for the support you have
been put, but It think next time I will cooshe politics free repo.

There are handful of them.

Thanks again for this wonderful package  📦 😘

**Comment by stalniy** [comment]
@Cholowao unfortunately, I can’t say anything good to people like you. Just would like to see you in my position, without electricity, with killed relatives, with a small child on your neck, with air attacks 2 times per week, talking to some stranger who says something about politics. 

Redirect your kisses to … ;)

**Comment by Todmy** [comment]
@Cholowao stop watching russian propaganda. Russia is killing people in Ukraine. I completely agree and support @stalniy.

**Comment by webknjaz** [comment]
Панове @stalniy @Todmy, можливо, вас зацікавить наш банер :)

https://github.com/vshymanskyy/StandWithUkraine FYI (не шлю патч одразу, бо не знаю чи ви віддаєте перевагу тому невеличкому посиланню з якихось причин)

**Comment by Cholowao** [comment]
Why you use Russian Language...

**Comment by webknjaz** [comment]
> Why you use Russian Language...

I don't. It's disgusting that you're assuming that 🤢

**Pull request closed without merging**
