### PR TITLE
fix(prisma): fix 'isNot' and 'none' condition

### LINKED ISSUE #536: Broken query operators from @casl/prisma
**Describe the bug**

Using `isNot` with `prismaQuery` (or anywhere else down the road) results in an interpreter error.

```ts
const test = prismaQuery({ test: { isNot: { id: 1 } } })
test({})
// -> Error: Unable to interpret "isNot" condition. Did you forget to register interpreter for it?
```

This is due to how [inverted](https://github.com/stalniy/casl/blob/c28d27a1579c2e3acb63c174f3f600d91b391b92/packages/casl-prisma/src/prisma/PrismaQueryParser.ts#L148) works (or "doesn't work).

As being called with `baseInstruction.parse` for the `isNot` operator results in the instruction being passed to the `.parse` function which doesn't know anything about `isNot` because it is not being passed to the `createJsInterpreter` function. Instead, `.parse` should be called with `is` operator, so after being wrapped in the `CompoundCondition('NOT', [condition])` we'll end up with `NOT: { is: {...} }`. Same applies to the `none` operator.

Additionally, the `none` operator is defined as `inverted('every', relation)` but should actually be defined as `inverted('some', relation)` as `none` means: "not even a single one" ([zero](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#none)) should match the condition.

```ts
// current:
const test = prismaQuery({ test: { none: { id: 1 } } })
test({ test: [{ id:1 }, { id:2 }] }) // true, but should be false

// expected:
const test = prismaQuery({ test: { none: { id: 1 } } })
test({ test: [{ id:1 }, { id:2 }] }) // false: ✅ because at least one element matches the condition
```

**CASL Version**

`@casl/ability` - v5.4.0
`@casl/prisma` - v1.0.0-alpha.2

### PR DESCRIPTION
**Pull request by jsbrain**
fixes #536

### CODE REVIEW

**Comment by stalniy** [comment]
Awesome! Thank you for the fix! I will look more closely into this tomorrow

**Comment by jsbrain** [comment]
My pleasure!

But I realize I probably shouldn't have merged this into master?

**Comment by stalniy** [comment]
That's fine, I'm merging alpha in master and will make a v1 release

**Comment by stalniy** [comment]
released in @casl/prisma@1.0.0 !

**Pull request merged**
