### PR TITLE
fix(typescript): add rulesToFields definition

### PR DESCRIPTION
**Pull request by vonagam**

### CODE REVIEW

**Comment by stalniy** [comment]
released in @casl/ability@3.1.0

**Comment by vonagam** [comment]
When will it be published?

**Comment by stalniy** [comment]
It must be available in npm, double check please

**Comment by vonagam** [comment]
Oh, sorry, i was checking with yarn and at the moment it [shows only 3.0.2](https://yarnpkg.com/en/package/@casl/ability). Seems like they have really long living cache.

**Pull request merged**
