### PR TITLE
feat: Angular 13 support (+rxjs 7)

### PR DESCRIPTION
**Pull request by gloaec**
Hi,

First of all, i read some of your messages about the situation you are living right now, and I am really sorry that you have to go through any of this. I hope the situation gets better soon.

This is our modest contribution (with [@MrP](https://github.com/VincentPuget)) to the project, i guess a couple of people are stuck migrating to Angular 13 rn :)

Anyway, let us know how we can help and get this merged. 
In the meantime, take care and be safe :*

Fixes : https://github.com/stalniy/casl/issues/601
Related MR : https://github.com/stalniy/casl/pull/580

### CODE REVIEW

**Comment by gloaec** [comment]
Sure, ppl will just change dependency to then new version I guess.

I don't know the release procedure through, should I do it or let you take things from here ?

Cheers

**Comment by gloaec** [comment]
Or maybe I missunderstood : you want to keep compatibility with Angular 12 ?

**Comment by stalniy** [comment]
ok let's merge it as it's. anyway, supporting multiple ng versions is a headache and starting from 13 there is no ViewEngine anymore what is good :)

**Comment by gloaec** [comment]
Alright :)

Thanks mate

**Pull request merged**
