### PR TITLE
Adapt Mongoose typings

### LINKED ISSUE #634: Mongoose with Typescript without “extends Document”
**Is your feature request related to a problem? Please describe.**

Mongoose recommends not to use `extends Document`. [According to them](https://mongoosejs.com/docs/typescript.html#using-extends-document), support for this will be dropped in the next major release and they claim that there are “major performance issues” (unfortunately without going into any details at all -- I would only guess they mean for running `tsc`?). 

> We strongly recommend against using this approach, its support will be dropped in the next major version as it causes major performance issues. Many Mongoose TypeScript codebases use the below approach.

However …

I have tried picking up their new recommendations and going without the `extends Document`. I've hit already several walls there, finally getting it work, but I'm now kind of stuck properly combining this with `@casl/mongoose`, which seems to assume the “deprecated” `extends Document` principle.

**Describe the solution you'd like**

Has anybody successfully managed to use `@casl/mongoose` with the new Mongoose-recommended structure? I would highly appreciate some sample code for that. Is it possible at all, or would the `@casl/mongoose` plugin need to be updated?

### PR DESCRIPTION
**Pull request by qqilihq**
* Allow to use without `extends Document` syntax
* Requires at least Mongoose 6.0.13 due to `HydratedDocument`
* See https://github.com/stalniy/casl/issues/634

Closes #634

### CODE REVIEW

**Comment by stalniy** [comment]
Looks good. Thank you! I need to test whether this doesn't introduce a breaking change due to interface change. at first look, all should be good

**Comment by ayush-goyal** [comment]
Any update on this?

**Comment by stalniy** [comment]
as peerDependency version was increased, I need to release a major version of casl/mongoose. Because technically it's a BC

**Comment by stalniy** [comment]
@qqilihq nice work! Thank you very much for the contribution! Sorry for the super long review.

**Comment by stalniy** [comment]
released in @casl/mongoose@7.0.0

**Comment by qqilihq** [comment]
@stalniy Great, thank you so much, highly appreciated! Awesome lib, keep it up!

**Comment by SteadEXE** [comment]
I was waiting for it. @stalniy you rocks.

**Pull request merged**
