### PR TITLE
docs(conditions): Add link to supported sift.js operators

### PR DESCRIPTION
**Pull request by sergio-toro**
Hey!

I spent a bunch of time trying to add a complex Regex condition because I couldn't find any operator helping in my use case to find out casl is using [sift.js](https://github.com/crcn/sift.js/tree/7.0.1) which supports `$nin` (It works).

Adding a link to the sift.js project and removing "Supports only" (which is not correct) will be helpful for folks with advanced use cases.

### CODE REVIEW

**Comment by stalniy** [comment]
Hi,

Thanks for the request! Frankly speaking this is what I don’t want to expose. I’m not sure how long CASL will use sift as the underlying library for condition checks. I actually want to switch to mingo, because it’s more structure and clear in terms of abstractions but currently it’s very heavy weight for the front end apps. 

sift is an internal implementation details. You may use it’s features but   I don’t guarantee that CASL will support it forever. That’s why I emphasized supported operators (sorry for missing `$nin`, I’ll add it). 

For advanced cases, CASL supports custom rule implementation injection (which is not documented currently). I’ll add this into docs after migrating to VuePress and making all examples to be more interactive. 

Read more details about custom rule implementation in this [comment](https://github.com/stalniy/casl/issues/149#issuecomment-455066292)

**Comment by sergio-toro** [comment]
@stalniy I see. Alright, if the plan is to move to another lib it should be fine!

I strongly recommend at least to review supported operators documentation, the typo in `regexp` (it is `regex`). And a link to the custom rule implementation would be nice.

It will be really helpful for new folks using the library.

Cheers!

**Comment by stalniy** [comment]
I see. Thanks for the feedback!

**Comment by stalniy** [comment]
Probably I need to document this with possible drawbacks

**Comment by stalniy** [comment]
Eventually decided to merge this. Thanks!

**Pull request merged**
