### PR TITLE
chore(deps): update angular to v15

### PR DESCRIPTION
**Pull request by mbarzda**
Update Angular to `15.0.0`.

Note: `jest-preset-angular` still has `peerDependencies` `Angular >=12.2.16 <15.0.0`

### CODE REVIEW

**Comment by Sayene** [comment]
jest-preset-angular has been updated to [12.2.3](https://github.com/thymikee/jest-preset-angular/compare/v12.2.2...v12.2.3), now supporting angular 15

**Comment by xbisa** [comment]
@serhiistotskyi  The errors in the build are related to the Vue package. It makes sense because you build everything, but it's not related to the changes the PR author made.

**Comment by robinNode** [comment]
hi @serhiistotskyi, 
Can we fix this issue asap? We cannot upgrade angular to v15 if we use CASL in the project. 
Thank a lot.

**Comment by xbisa** [comment]
If you download the log archive, you can see the problem is the following

`2022-11-21T19:26:51.9534534Z packages/casl-vue prebuild: ../../node_modules/.pnpm/@vue/runtime-core@3.0.11/node_modules/@vue/runtime-core/dist/runtime-core.d.ts(1334,33): error TS2344: Type 'HostElement' does not satisfy the constraint 'RendererElement'.`

Vue ships with erroneous type definitions. A workaround is stetting "skipLibCheck": true in tsconfig.json:

```
{
  "extends": "../../tsconfig",
  "include": [
    "src/*",
    "spec/*"
  ],
  "compilerOptions": {
    "outDir": "dist/types",
    "types": ["vue"],
    "skipLibCheck": true
  }
}
```

@serhiistotskyi can you accept this solution?

**Comment by stalniy** [comment]
The issue in vuejs has been fixed in summer -> https://github.com/vuejs/core/issues/6554

is it possible to update angular without updating typescript to 4.8.x? 

If not, the the proper fix in this case is to fix vuejs first. I’ll try to look into this tomorrow.

**Comment by Sayene** [comment]
Thanks @stalniy,
Angular v15 requires TypeScript version 4.8 or later [see](https://angular.io/guide/update-to-version-15)

**Comment by stalniy** [comment]
released in @casl/angular@8.2.0

**Comment by xbisa** [comment]
Thanks @stalniy. Very appreciated.

**Pull request merged**
