### PR TITLE
feat(prisma): Add 'isSet' filter to prisma filters

### PR DESCRIPTION
**Pull request by p0thi**
As mentioned in #966 , using the `isSet` filter for optional field in prisma with mongodb is currently not possible.

This PR adds this functionality:

- Add a new 'isSet' field instruction to PrismaQueryParser.
- The 'isSet' instruction checks if an object value is defined when using the 'isSet' condition in a query.
- Update the interpretPrismaQuery function to handle the new 'isSet' instruction.

### CODE REVIEW

**Comment by stalniy** [comment]
looks like there is some issue with env stuff, I will take a look but this will take some time. Thanks for contribution

**Comment by p0thi** [comment]
> looks like there is some issue with env stuff, I will take a look but this will take some time. Thanks for contribution

Thanks! Did I introduce this issues?

**Comment by stalniy** [comment]
THe issue relates to GHA, it doesn't share GH_TOKEN with non-collaborators, that's why GHA fails because it cannot run `release` action which should post a comment with explanation of what is changed and what is the next version.

I introduced this recently as part of automatic release management gha and tested it under my account, and obviously it worked because I'm the owner.

I'll try to find solution, if won't be able to do it, I will need to change release gha to be manual and then I'll trigger it via button

**Comment by stalniy** [comment]
Will release it during the next week. Cannot make it work for automated releases. Need more investigation

**Comment by stalniy** [comment]
released in @casl/prisma@1.5.0 

Sorry for the long delay

**Pull request merged**
