### PR TITLE
Fix default error message in cases where subject is a class

### PR DESCRIPTION
**Pull request by Alex0007**
Fixes ForbiddenError messages like this:

```
ForbiddenError: Cannot execute "read" on "function model(doc, fields, skipId) {
      model.hooks.execPreSync('createModel', doc);
[...]
```

### CODE REVIEW

**Comment by stalniy** [comment]
I can't understand how this can be possible. `error.subjectType` is always expected to be a string. I've just added test to casl/ability and it works as expected.

```
it('correctly extracts subject type name from class subject types', () => {
      class Post {}

      const ability = new PureAbility([
        { action: 'read', subject: Post }
      ], {
        detectSubjectType: o => o.constructor as SubjectType
      });

      try {
        ForbiddenError.from(ability).throwUnlessCan('update', Post);
        expect('this code').toBe('never reached');
      } catch (error) {
        expect((error as ForbiddenError<PureAbility>).subjectType).toBe('Post');
        expect((error as ForbiddenError<PureAbility>).message).toBe('Cannot execute "update" on "Post"');
      }
    })
```

later I tried to do the same in context of mongoose it got the same result. 

Can you share your ability setup and test code?

**Comment by Alex0007** [comment]
```typescript
import { AbilityBuilder, Ability, defineAbility } from '@casl/ability';
import mongoose from 'mongoose';

const { accessibleRecordsPlugin } = require('@casl/mongoose')

const Article = new mongoose.Schema({
  title: String,
  author: String
})

Article.plugin(accessibleRecordsPlugin)

const ArticleModel = mongoose.model('Article', Article)

const ability = defineAbility((can, cannot) => {
  cannot('read', ArticleModel)
}, {
  detectSubjectType: object => object.constructor as any
})

ArticleModel.accessibleBy(ability).findOne().then(console.log).catch(console.error)
```

**Comment by Alex0007** [comment]
@stalniy 

```typescript
import { AbilityBuilder, Ability, defineAbility } from '@casl/ability';
import mongoose from 'mongoose';

const { accessibleRecordsPlugin } = require('@casl/mongoose')

const Article = new mongoose.Schema({
  title: String,
  author: String
})

Article.plugin(accessibleRecordsPlugin)

const ArticleModel = mongoose.model('Article', Article)

const ability = defineAbility((can, cannot) => {
  cannot('read', ArticleModel)
}, {
  detectSubjectType: object => object.constructor as any
})

ArticleModel.accessibleBy(ability).findOne().then(console.log).catch(console.error)
```

**Comment by Alex0007** [comment]
Not sure how to run test, but i guess [here](https://github.com/stalniy/casl/blob/master/packages/casl-mongoose/spec/accessible_records.spec.ts#L131) i can get same incorrect error message. 

But subject name is not checking there

**Comment by stalniy** [comment]
ok the issue is in casl/mongoose package

**Comment by stalniy** [comment]
fixed in @casl/mongoose@7.1.2 and @casl/ability@6.3.2

**Pull request closed without merging**
